version: '3.4'

services:
  backend:
    image: commenti_server
    build:
      context: .
      dockerfile: ./Dockerfile
    expose:
      - "8000"
    env_file: .env
    depends_on:
      - database
    environment:
      - STATIC_ROOT=/static
    volumes:
      - static:/static

  nginx:
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static
    ports:
      - 8012:8080

  database:
    image: postgres:13.2
    volumes:
      - pgsql:/var/lib/postgresql/data
    expose:
      - "5432"
    env_file: .env.postgres

volumes:
  pgsql:
  static:
