# Generated by Django 3.2.5 on 2021-07-05 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20210705_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='comments.page', verbose_name='Page'),
            preserve_default=False,
        ),
    ]
